/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionBar: typeof import('./components/chat/ActionBar.vue')['default']
    AppHeader: typeof import('./components/layout/AppHeader.vue')['default']
    ChatInput: typeof import('./components/chat/ChatInput.vue')['default']
    ContentCandidateCard: typeof import('./components/chat/content/ContentCandidateCard.vue')['default']
    EpisodeAnalysisPanel: typeof import('./components/session/EpisodeAnalysisPanel.vue')['default']
    GenericContent: typeof import('./components/chat/content/GenericContent.vue')['default']
    LocalFilePicker: typeof import('./components/common/LocalFilePicker.vue')['default']
    ManifestCard: typeof import('./components/chat/content/ManifestCard.vue')['default']
    MarkdownContent: typeof import('./components/chat/content/MarkdownContent.vue')['default']
    MessageList: typeof import('./components/chat/MessageList.vue')['default']
    PlanCandidateCard: typeof import('./components/chat/content/PlanCandidateCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StoryboardCutCard: typeof import('./components/chat/content/StoryboardCutCard.vue')['default']
    SupervisorResultCard: typeof import('./components/chat/content/SupervisorResultCard.vue')['default']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TextContent: typeof import('./components/chat/content/TextContent.vue')['default']
    ThinkingContent: typeof import('./components/chat/content/ThinkingContent.vue')['default']
    TInput: typeof import('tdesign-vue-next')['Input']
    TLink: typeof import('tdesign-vue-next')['Link']
    TOption: typeof import('tdesign-vue-next')['Option']
    TPopconfirm: typeof import('tdesign-vue-next')['Popconfirm']
    TSelect: typeof import('tdesign-vue-next')['Select']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTable: typeof import('tdesign-vue-next')['Table']
    TTag: typeof import('tdesign-vue-next')['Tag']
    TTextarea: typeof import('tdesign-vue-next')['Textarea']
    VideoCandidateCard: typeof import('./components/chat/content/VideoCandidateCard.vue')['default']
  }
}
